### ISSUE TITLE
Provide JAM codec test vectors

### ISSUE THREAD

**Issue by xlc** [w3f/jamtestvectors#10]
Currently SCALE test vectors are provided but it is not that useful as we are not using SCALE codec in GP.
Instead, JAM codec one should be provided so we can test the codec part of the implementation.

**Comment by xlc** [comment]
If switch codec is trivial, can you just switch scale to codec to jam codec?

JSON serialization is not part of the protocol and requires extra work and jam codec is part of the protocol and requires no extra work.

**Comment by davxy** [comment]
> If switch codec is trivial, can you just switch scale to codec to jam codec?

Offcourse we will, when codec implementation is ready. Once ready, switching codec is trivial. 

> JSON serialization is not part of the protocol and requires extra work and jam codec is part of the protocol and requires no extra work.

JSON has been mainained to offer a human readable version of the binary file for quick inspection. It is basically free to generate.

**Comment by xlc** [comment]
In that case can I request someone to prioritize the jam codec implementation and test vectors? Or let me know if it won't be done in next few weeks then in that case I will spend some hours to support the JSON format.

**Comment by davxy** [comment]
https://github.com/w3f/jamtestvectors/pull/12
